#!/usr/bin/python

import csv
import os
from Bio import SeqIO
import sys


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print """
            Usage: ./fasta_to_bed <dir>
                where dir is folder with fasta files
                which need converting """
    path = sys.argv[1]
    rowcount = 0
    for fpath in os.listdir(path):
        if fpath.endswith(".fa"):
            fname, ext = fpath.split(".")
            bedfile = "bed/%s.bed" % fname
            print "Outputting %s to %s" % (("fasta/" + fname, bedfile))
            with open(os.path.join("fasta", fpath)) as f, open(bedfile, "w") as out:
                writer = csv.writer(out, delimiter="\t", lineterminator="\n")
                fasta_file = SeqIO.parse(f, 'fasta')
                for entry in fasta_file:
                    writer.writerow(entry.id.split("."))
                    rowcount += 1
                print "%d rows written" % rowcount
